import type { Metadata } from 'next';
import { NextUIProvider } from '@nextui-org/react';
import { Inter } from 'next/font/google';
import StoreProvider from '@/redux/storeProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Demo Lounges App',
    description: 'Generated by Minh',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StoreProvider>
                    <NextUIProvider>{children}</NextUIProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
